### ISSUE TITLE
Value should be a Json Object 

### ISSUE THREAD

**Issue by Meet2147** [romainsi/zabbix-scheduledtask#1]
When i attach this template to the agent i get an error stating the "value should be json object " but the status of the template is enabled and it gives no output .

Please help

**Comment by romainsi** [comment]
Hi, I recently updated the script but ... are you sure the variable in powershell script is correct?
You can start the script as follows:
.\DiscoverScheduledTasks.ps1 DiscoverTasks 
And verified that it returns a JSON value?
