### ISSUE TITLE
In 3.4.5 agent and Win 10 WinServer 2012 R2 not working

### ISSUE THREAD

**Issue by adymer** [romainsi/zabbix-scheduledtask#3]
In Zabbix 3.4.5 template does not work.With Windows 10 In "Configuration" -> "Hosts" -> "Discovery rules" status "Not supported" and error "Value should be a JSON object" and with Win Server 2012 R2
 In "Configuration" -> "Hosts" -> "Discovery rules" status "Enabled" and error "Value should be a JSON object"

**Comment by romainsi** [comment]
Hi,

It works with Windows 2012R2 and zabbix 3.4.9.
Please modify variable $path
