### ISSUE TITLE
Add remark about Timeout parameter.

### ISSUE THREAD

**Issue by NemoDima** [romainsi/zabbix-scheduledtask#4]
Hi @romainsi 
About https://github.com/romainsi/zabbix-scheduledtask/tree/master/Zabbix%20v3.4
At the first time on discovery rule, I got "Timeout while executing a shell script." message.
And it was solved after I have changed the Timeout parameter on an agent in the zabbix_agentd.conf from the default  3 to a higher value(I set 30).
For this reason, I think it has the sense to add a remark about the possible message and parameter.
Regards.

**Comment by romainsi** [comment]
Done :)
Thx 👍
