### ISSUE TITLE
Error when try to add translated tamplate.

### ISSUE THREAD

**Issue by NemoDima** [romainsi/zabbix-scheduledtask#5]
@romainsi hi again
https://github.com/romainsi/zabbix-scheduledtask/tree/master/Zabbix%20v3.4
I translated your zbx3.4_export_templates.xml to English(please check the added file).
But when I try to add this template, I get "Application with ID "" is not available on "Template ..." error. I checked it a few times, but can't understand the reason for the error.
Tell me please, do you know why it could be so?
[zbx3.4_export_templ_en.xml.zip](https://github.com/romainsi/zabbix-scheduledtask/files/3440622/zbx3.4_export_templ_en.xml.zip)
Best wishes!

**Comment by romainsi** [comment]
Hi, please translate in zabbix template and export after because edited xml not easy ...
